### ISSUE TITLE
Issues with 5.0.2

### ISSUE THREAD

**Issue by lstagner** [cmacmackin/ford#154]
The latest update has broken my build in two different ways.

The first is that images on my website have broken (http://d3denergetic.github.io/FIDASIM/)
The website is automatically generated when I push. Here is the [build log](https://travis-ci.org/D3DEnergetic/FIDASIM/builds/147618590#L335)

Secondly, when I try to build the docs locally I get the following  error
```
...
Generating graphs...
Creating HTML documentation...
Creating search index...
Traceback (most recent call last):
  File "/home/lstagner/anaconda3/bin/ford", line 11, in <module>
    sys.exit(run())
  File "/home/lstagner/anaconda3/lib/python3.5/site-packages/ford/__init__.py", line 359, in run
    main(proj_data,proj_docs,md)
  File "/home/lstagner/anaconda3/lib/python3.5/site-packages/ford/__init__.py", line 346, in main
    docs = ford.output.Documentation(proj_data,proj_docs_,project,page_tree)
  File "/home/lstagner/anaconda3/lib/python3.5/site-packages/ford/output.py", line 142, in __init__
    self.tipue.create_node(p.html,p.loc,p.obj.meta)
  File "/home/lstagner/anaconda3/lib/python3.5/site-packages/ford/tipue_search.py", line 61, in create_node
    soup = BeautifulSoup(html,'lxml')
  File "/home/lstagner/anaconda3/lib/python3.5/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/lstagner/anaconda3/lib/python3.5/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/lstagner/anaconda3/lib/python3.5/site-packages/bs4/builder/_lxml.py", line 247, in feed
    self.parser.feed(markup)
  File "src/lxml/parser.pxi", line 1205, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:112201)
  File "src/lxml/parser.pxi", line 1327, in lxml.etree._FeedParser.feed (src/lxml/lxml.etree.c:112076)
  File "src/lxml/parsertarget.pxi", line 141, in lxml.etree._TargetParserContext._handleParseResult (src/lxml/lxml.etree.c:128525)
  File "src/lxml/parsertarget.pxi", line 135, in lxml.etree._TargetParserContext._handleParseResult (src/lxml/lxml.etree.c:128395)
  File "src/lxml/lxml.etree.pyx", line 324, in lxml.etree._ExceptionContext._raise_if_stored (src/lxml/lxml.etree.c:10740)
  File "src/lxml/saxparser.pxi", line 549, in lxml.etree._handleSaxPI (src/lxml/lxml.etree.c:123433)
  File "src/lxml/parsertarget.pxi", line 94, in lxml.etree._PythonSaxParserTarget._handleSaxPi (src/lxml/lxml.etree.c:127883)
  File "/home/lstagner/anaconda3/lib/python3.5/site-packages/bs4/builder/_lxml.py", line 211, in pi
    self.soup.endData(self.processing_instruction_class)
AttributeError: 'LXMLTreeBuilder' object has no attribute 'processing_instruction_class'
```

**Comment by cmacmackin** [comment]
The reason your images aren't showing is because one of the non-backwards-compatible changes introduced with v5.0.0 (and listed in the [release notes](https://github.com/cmacmackin/ford/releases/tag/v5.0.0)) was paths now being evaluated relative to the project file rather than relative to the PWD. As such, you should have `media_dir: ./media` and `favicon: ./media/fidasim-favicon.png`. I did catch a bug wherein paths specified from the command line are being evaluated this way too, which they are not supposed to be. I also picked up a small bug which I introduced when I tidied up the handling of attribute declarations. This made itself visible in your build log and would have meant that there was no documentation produced for `parallel_rng.f90`. I've fixed these and released them as v5.0.3.

I don't know what the issue is with the bug you experienced when using FORD locally and could not reproduce it on my Linux Mint 17.3 laptop, using Python 2.7. I don't understand how that could have been introduced with the new version, as I haven't touched that bit of the code in quite awhile. The problem seems to be making itself felt at quite a low level in BeautifulSoup4/LXML. Have you been able to run FORD locally on this project in previous versions? Would you mind testing this with v4.6.2?

**Comment by lstagner** [comment]
I made your suggested changes with regards to the media directory and its still broken.
https://travis-ci.org/D3DEnergetic/FIDASIM/builds/147647669#L423

I was previously able to build locally with all the other versions of FORD. I am using python3 but I ran FORD with python2 and the problem persists.

**Comment by cmacmackin** [comment]
Update to 5.0.4 and the build should work on travis-ci.

Addressing the issue with local builds, could you please post the output from running `pip freeze` in the virtualenv where you have FORD installed?

**Comment by lstagner** [comment]
Thanks travis build is fixed. 

Here is the output of ```pip freeze```
```
lstagner@computer:~/FIDASIM$ pip freeze
abstract-rendering==0.5.1
alabaster==0.7.7
anaconda-client==1.4.0
anaconda-navigator==1.1.0
argcomplete==1.0.0
astropy==1.1.2
attrs==15.2.0
Babel==2.2.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.0
bitarray==0.8.1
blaze==0.9.0
bokeh==0.11.1
boto==2.39.0
Bottleneck==1.0.0
cffi==1.5.2
chest==0.2.3
cloudpickle==0.1.1
clyent==1.2.1
colorama==0.3.7
conda==4.1.11
conda-build==1.19.0
conda-env==2.5.0a0
conda-manager==0.3.1
configobj==5.0.6
cryptography==1.3
cssselect==0.9.1
cycler==0.10.0
Cython==0.23.4
cytoolz==0.7.5
dask==0.8.1
datashape==0.5.1
decorator==4.0.9
dill==0.2.4
docutils==0.12
dynd==0.7.3.dev1
et-xmlfile==1.0.1
fastcache==1.0.2
Flask==0.10.1
Flask-Cors==2.1.2
FORD==5.0.4
futures==3.0.3
gevent==1.1.0
graphviz==0.4.10
greenlet==0.4.9
h5py==2.5.0
HeapDict==1.0.0
idna==2.0
ipykernel==4.3.1
ipython==4.1.2
ipython-genutils==0.1.0
ipywidgets==4.1.1
itsdangerous==0.24
jdcal==1.2
jedi==0.9.0
Jinja2==2.8
jsonschema==2.4.0
jupyter==1.0.0
jupyter-client==4.2.2
jupyter-console==4.1.1
jupyter-core==4.1.0
llvmlite==0.9.0
locket==0.2.0
lxml==3.6.1
Markdown==2.6.6
markdown-include==0.5.1
MarkupSafe==0.23
matplotlib==1.5.1
md-environ==0.1.0
mistune==0.7.2
mpmath==0.19
multipledispatch==0.4.8
nbconvert==4.1.0
nbformat==4.0.1
networkx==1.11
nltk==3.2
nose==1.3.7
notebook==4.1.0
numba==0.24.0
numexpr==2.5
numpy==1.10.4
odo==0.4.2
openpyxl==2.3.2
pandas==0.18.0
partd==0.3.2
path.py==0.0.0
patsy==0.4.0
pep8==1.7.0
pexpect==4.0.1
pickleshare==0.5
Pillow==3.1.1
ply==3.8
prompt-toolkit==1.0.3
psutil==4.1.0
ptyprocess==0.5
py==1.4.31
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.19.5.3
pyflakes==1.1.0
Pygments==2.1.3
pyOpenSSL==0.15.1
pyparsing==2.0.3
pytest==2.8.5
python-dateutil==2.5.1
pytz==2016.2
PyYAML==3.11
pyzmq==15.2.0
QtAwesome==0.3.2
qtconsole==4.2.0
QtPy==1.0
queuelib==1.4.2
redis==2.10.3
requests==2.9.1
rope-py3k==0.9.4.post1
ruamel-yaml===-VERSION
scikit-image==0.12.3
scikit-learn==0.17.1
scipy==0.17.0
Scrapy==1.0.5
service-identity==16.0.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.1
Sphinx==1.3.5
sphinx-rtd-theme==0.1.9
spyder==2.3.8
SQLAlchemy==1.0.12
statsmodels==0.6.1
sympy==1.0
tables==3.2.2
terminado==0.5
toolz==0.7.4
toposort==1.4
tornado==4.3
traitlets==4.2.1
Twisted==16.1.0
unicodecsv==0.14.1
w3lib==1.14.1
wcwidth==0.1.7
Werkzeug==0.11.4
xlrd==0.9.4
XlsxWriter==0.8.4
xlwt==1.0.0
zope.interface==4.1.3
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
lstagner@computer:~/FIDASIM$ 
```

**Comment by sponce24** [comment]
Hello, 

Just to say that I have the same issue:

```
Generating graphs...
Creating HTML documentation...
Creating search index...
Traceback (most recent call last):
  File "/usr/local/bin/ford", line 9, in <module>
    load_entry_point('FORD==5.0.4', 'console_scripts', 'ford')()
  File "/usr/local/lib/python3.4/dist-packages/ford/__init__.py", line 356, in run
    main(proj_data,proj_docs,md)
  File "/usr/local/lib/python3.4/dist-packages/ford/__init__.py", line 343, in main
    docs = ford.output.Documentation(proj_data,proj_docs_,project,page_tree)
  File "/usr/local/lib/python3.4/dist-packages/ford/output.py", line 142, in __init__
    self.tipue.create_node(p.html,p.loc,p.obj.meta)
  File "/usr/local/lib/python3.4/dist-packages/ford/tipue_search.py", line 61, in create_node
    soup = BeautifulSoup(html,'lxml')
  File "/usr/local/lib/python3.4/dist-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/usr/local/lib/python3.4/dist-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/usr/local/lib/python3.4/dist-packages/bs4/builder/_lxml.py", line 248, in feed
    self.parser.close()
  File "parser.pxi", line 1283, in lxml.etree._FeedParser.close (src/lxml/lxml.etree.c:98831)
  File "parser.pxi", line 1313, in lxml.etree._FeedParser.close (src/lxml/lxml.etree.c:98680)
  File "parsertarget.pxi", line 136, in lxml.etree._TargetParserContext._handleParseResult (src/lxml/lxml.etree.c:112755)
  File "parsertarget.pxi", line 130, in lxml.etree._TargetParserContext._handleParseResult (src/lxml/lxml.etree.c:112662)
  File "lxml.etree.pyx", line 327, in lxml.etree._ExceptionContext._raise_if_stored (src/lxml/lxml.etree.c:10196)
  File "saxparser.pxi", line 549, in lxml.etree._handleSaxPI (src/lxml/lxml.etree.c:108447)
  File "parsertarget.pxi", line 89, in lxml.etree._PythonSaxParserTarget._handleSaxPi (src/lxml/lxml.etree.c:112212)
  File "/usr/local/lib/python3.4/dist-packages/bs4/builder/_lxml.py", line 211, in pi
    self.soup.endData(self.processing_instruction_class)
AttributeError: 'LXMLTreeBuilder' object has no attribute 'processing_instruction_class'
```

I tested with python 2.7 and pip and with python 3.4.3 and pip3. Both give the same error message.

pip3 freeze gives

```

Brlapi==0.6.1
FORD==5.0.4
Jinja2==2.8
Mako==0.9.1
Markdown==2.6.6
MarkupSafe==0.18
Pygments==2.1.3
apturl==0.5.2ubuntu4
beautifulsoup4==4.5.0
chardet==2.2.1
checkbox-ng==0.3
checkbox-support==0.2
colorama==0.2.5
command-not-found==0.3
defer==1.0.6
feedparser==5.1.3
friends==0.1
graphviz==0.4.10
html5lib==0.999
httplib2==0.8
language-selector==0.1
louis==2.5.3
lxml==3.3.3
markdown-include==0.5.1
md-environ==0.1.0
oauthlib==0.6.1
onboard==1.0.1
oneconf==0.3.7.14.04.1
piston-mini-client==0.7.5
plainbox==0.5.3
pycrypto==2.6.1
pycurl==7.19.3
pygobject==3.12.0
pyparsing==2.0.1
python-apt==0.9.3.5ubuntu2
python-debian==0.1.21-nmu2ubuntu2
pyxdg==0.25
requests==2.2.1
six==1.5.2
software-center-aptd-plugins==0.0.0
toposort==1.4
ubuntu-drivers-common==0.0.0
ufw==0.34-rc-0ubuntu2
unattended-upgrades==0.1
unity-scope-audacious==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-clementine==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-gmusicbrowser==0.1
unity-scope-gourmet==0.1
unity-scope-guayadeque==0.1
unity-scope-manpages==0.1
unity-scope-musique==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
unity-tweak-tool==0.0.6
urllib3==1.7.1
usb-creator==0.2.23
wheel==0.24.0
xdiagnose==3.6.3build2
xkit==0.0.0

Best, 

Samuel
 

```

**Comment by cmacmackin** [comment]
Okay, I've made progress in finding the source of the problem. FORD can use two different libraries when generating the search index: the default built into BS4 (whose name I forget) and lxml. The latter is faster but requires python development packages from the system package manager to be installed in order for `pip` to install it properly. As such, I did not make it a requirement and just added a line so that FORD will use it if it is available. The problem here arises if you are generating a search index, when graphs are being generated, if LXML is being used. I had turned off graphs and the search feature during my initial investigations in order to make FORD run more quickly, hence why I initially could not reproduce this bug.

What is odd is that you claim to only be experiencing this error now. Going back through old versions, I found that this problem arises even in the first commit where LXML was used. Perhaps you just haven't had it installed up until now?

Anyway, I need to figure out what the issue could be with the graphs which is causing LXML to crash. This, I confess, is not entirely clear to me. In the meantime, you could uninstall lxml (or run FORD from a virtualenv without it installed) as a workaround.

**Comment by sponce24** [comment]
Hello Chris, 

I confirm that it works for me by removing the python-lxml

Thank you, 

Best, 

Samuel

**Comment by cmacmackin** [comment]
I've found that newer versions of beautifulsoup seem to have fixed this problem. I've updated the dependency information accordingly.

**Comment by cmacmackin** [comment]
Just authored a release fixing this.
